apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBhz6qxSRN8Z9LE/33N6ezbRJbciz5r+IbA+DeVoPaSlfkfd/PINTgUTA9RFm+bzjTk4CHz0elYuh2wiaLdUMnhZrwxzBL4l2rLRzJ/3plPrtTjdZdxCc3fxkZhTFQZ6UocoeS4mjW64WkOzNBufs/9mKSpo69QzNMuUUexIeWtS7uEusKnHJC0xQZN8Lkcw/hrnnZdJ3jOgfS+noteKg6E/BmdzLQlpmXLEy+/jJ3HoDXvEcNT5Mm/yMsE8+tYEgEYovDYm3wKqjxkAOdiY1MVG4nRX+5J9SVeZOso3e4nOXgCGNIZdchsM8wJSBBhnRBm+ZuFz1BiTc9/4PwhuC+/2rEXnhszMxiLbQA5t7oR037T47KWcXK3Sl4HyDIu29sqEYN7KIGTQLIFvC8IXbppzoAZooLLwWd0n6k8TQvFqGOoB/LrdXwkO6pMFHR59avLpChcsdUHTiVOluQay13ViX61TTAd5ydULb/kGnj9Plic7OILT209w/UtBQnmMwkPezqf/hbx3O/zAu/PGMggbpo+9dPwAqb21nMm5iXSMlUsQ4fz1ZAIu9fBaWP5FnnJhqdMMCUFdjdF6DsZbLY+5niGJ4EluKnn/kAL6234Ru99S3+vLQCEp5HXiDrEm1Os8ep5q22pH+g7lgI7oCjLAaALMW0rLurHFnEDE/QXj30BeTUGdZfD8Vm7qq+uKjT0401zWe2tJw==
    DB_USER: AgAYZ771sHvS0fB6p++YmuvOkroKyZVyAmqXKaWoZW/A24efuvo8T+JqBMH6gGfEZXX812hVeiSURWn36sy9TaxCLt0LQagQC9CbhT6N3NdVT233oAQD7agDRJYh08//86NKIbXNw4aG1D8gAXlH4k523b3Hh31ST2WzkgeZ7ZrUcgZcMf7N8E7zM0NDrLrn3ebsos8E1bv4lMKalYJXvROA8K1jCYeivskd87X7l0D8L8dyNi6N6ZzItoRINxzd5/j9Ex9IdXyxHfGZzFnE15QtpBxLzULhWjcGR3GYnSwOiyaQdslnGuXsYf0203e6R2Hw5TA08IMz0/U4zTAU7Nv49PolTiFNd75dgGZPMw/R/9bHJKdN1yjZegpgXfEuhAwXlVFTdWrEIKX9awsExCN2nShyLsFV9sWKp+RWsJ7SjKi6iHU0gPLwi+1rpp2YAa5afDwwfqIdcUcm7+GBGQiseqOBwbL2DaSDttc+Uc5K3UT86Ls4LfGwDdlfgsRNG5EKWAI5sRequZKA5stteoTv+xSQOpacGgJNoefJvZw7bsuPnvXa071MiQk+q2mdnIiifArj3edtW+pJkCICXLDrFU8ThWoLS+Qt9V8kqTjRrw2Xr5hke6v67hddGtFaqDc0fWVCkK65cPLhFsOZXFEszd0Q3aCLd/yPe14zdMYyC7x48L6uxQewK72k0sJIMysn7X8OfJ2EGQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

